global:
  scrape_interval: 15s

scrape_configs:
  - job_name: fitforge-backend
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: fitforge-subscriptions
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["localhost:8081"]
