/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/workouts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workouts */
        get: operations["list_workouts_api_v1_workouts__get"];
        put?: never;
        /** Create Workout */
        post: operations["create_workout_api_v1_workouts__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts/{workout_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workout */
        get: operations["get_workout_api_v1_workouts__workout_id__get"];
        put?: never;
        post?: never;
        /** Delete Workout */
        delete: operations["delete_workout_api_v1_workouts__workout_id__delete"];
        options?: never;
        head?: never;
        /** Update Workout */
        patch: operations["update_workout_api_v1_workouts__workout_id__patch"];
        trace?: never;
    };
    "/api/v1/workouts/{workout_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_api_v1_workouts__workout_id__sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_workouts__workout_id__sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exercises/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exercises */
        get: operations["list_exercises_api_v1_exercises__get"];
        put?: never;
        /** Create Exercise */
        post: operations["create_exercise_api_v1_exercises__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nutrition/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Entry */
        post: operations["create_entry_api_v1_nutrition__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nutrition/day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary For Day */
        get: operations["summary_for_day_api_v1_nutrition_day_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nutrition/day/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entries For Day */
        get: operations["entries_for_day_api_v1_nutrition_day_entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nutrition/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entry */
        get: operations["get_entry_api_v1_nutrition__entry_id__get"];
        put?: never;
        post?: never;
        /** Delete Entry */
        delete: operations["delete_entry_api_v1_nutrition__entry_id__delete"];
        options?: never;
        head?: never;
        /** Update Entry */
        patch: operations["update_entry_api_v1_nutrition__entry_id__patch"];
        trace?: never;
    };
    "/api/v1/notifications/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Test */
        post: operations["send_test_api_v1_notifications_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entitlements/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Entitlements */
        get: operations["get_my_entitlements_api_v1_entitlements_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Purchase Subscription */
        post: operations["purchase_subscription_api_v1_subscriptions_purchase_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Subscription */
        post: operations["cancel_subscription_api_v1_subscriptions_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analytics Summary */
        get: operations["get_analytics_summary_api_v1_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/enhanced": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Enhanced Analytics */
        get: operations["get_enhanced_analytics_api_v1_analytics_enhanced_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Daily Plan */
        get: operations["get_daily_plan_api_v1_plans_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/week": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Week */
        get: operations["get_week_api_v1_plans_week_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workout-plans/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate */
        post: operations["generate_api_v1_workout_plans_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workout-plans/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Active */
        get: operations["get_active_api_v1_workout_plans_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workout-plans/plan-day-exercises/{plan_day_exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Plan Day Exercise */
        patch: operations["update_plan_day_exercise_api_v1_workout_plans_plan_day_exercises__plan_day_exercise_id__patch"];
        trace?: never;
    };
    "/api/v1/workout-logs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Logs */
        get: operations["list_logs_api_v1_workout_logs__get"];
        put?: never;
        /** Create Log */
        post: operations["create_log_api_v1_workout_logs__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workout-logs/personal-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Personal Records */
        get: operations["list_personal_records_api_v1_workout_logs_personal_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/body-measurements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Measurements */
        get: operations["list_measurements_api_v1_body_measurements__get"];
        put?: never;
        /** Create Measurement */
        post: operations["create_measurement_api_v1_body_measurements__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/body-measurements/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Latest */
        get: operations["get_latest_api_v1_body_measurements_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/body-measurements/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trend */
        get: operations["get_trend_api_v1_body_measurements_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/body-measurements/{measurement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Measurement */
        get: operations["get_measurement_api_v1_body_measurements__measurement_id__get"];
        put?: never;
        post?: never;
        /** Delete Measurement */
        delete: operations["delete_measurement_api_v1_body_measurements__measurement_id__delete"];
        options?: never;
        head?: never;
        /** Update Measurement */
        patch: operations["update_measurement_api_v1_body_measurements__measurement_id__patch"];
        trace?: never;
    };
    "/api/v1/gamification/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Gamification */
        get: operations["get_gamification_api_v1_gamification_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Follow */
        post: operations["follow_api_v1_social_follow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/follow/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unfollow */
        delete: operations["unfollow_api_v1_social_follow__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Followers */
        get: operations["get_followers_api_v1_social_followers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Following */
        get: operations["get_following_api_v1_social_following_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Users */
        get: operations["search_users_api_v1_social_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/profile/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_social_profile__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Challenges */
        get: operations["list_my_challenges_api_v1_social_challenges_get"];
        put?: never;
        /** Create Challenge */
        post: operations["create_challenge_api_v1_social_challenges_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/challenges/{challenge_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join Challenge */
        post: operations["join_challenge_api_v1_social_challenges__challenge_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/challenges/{challenge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Challenge */
        get: operations["get_challenge_api_v1_social_challenges__challenge_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leaderboard */
        get: operations["get_leaderboard_api_v1_social_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/social/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity Feed */
        get: operations["get_activity_feed_api_v1_social_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AchievementRead */
        AchievementRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Badge Type */
            badge_type: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Icon */
            icon: string;
            /** Xp Earned */
            xp_earned: number;
            /**
             * Earned At
             * Format: date
             */
            earned_at: string;
        };
        /** AnalyticsSummary */
        AnalyticsSummary: {
            /** Total Workouts */
            total_workouts: number;
            /** Total Sessions */
            total_sessions: number;
            /** Total Sets */
            total_sets: number;
            /** Most Recent Workout */
            most_recent_workout?: string | null;
        };
        /** BodyMeasurementCreate */
        BodyMeasurementCreate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Body Fat Pct */
            body_fat_pct?: number | null;
            /** Chest Cm */
            chest_cm?: number | null;
            /** Waist Cm */
            waist_cm?: number | null;
            /** Hips Cm */
            hips_cm?: number | null;
            /** Arms Cm */
            arms_cm?: number | null;
            /** Thighs Cm */
            thighs_cm?: number | null;
        };
        /** BodyMeasurementRead */
        BodyMeasurementRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Body Fat Pct */
            body_fat_pct?: number | null;
            /** Chest Cm */
            chest_cm?: number | null;
            /** Waist Cm */
            waist_cm?: number | null;
            /** Hips Cm */
            hips_cm?: number | null;
            /** Arms Cm */
            arms_cm?: number | null;
            /** Thighs Cm */
            thighs_cm?: number | null;
        };
        /** BodyMeasurementUpdate */
        BodyMeasurementUpdate: {
            /** Weight Kg */
            weight_kg?: number | null;
            /** Body Fat Pct */
            body_fat_pct?: number | null;
            /** Chest Cm */
            chest_cm?: number | null;
            /** Waist Cm */
            waist_cm?: number | null;
            /** Hips Cm */
            hips_cm?: number | null;
            /** Arms Cm */
            arms_cm?: number | null;
            /** Thighs Cm */
            thighs_cm?: number | null;
        };
        /** BodyTrend */
        BodyTrend: {
            /** Date */
            date: string;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Body Fat Pct */
            body_fat_pct?: number | null;
            /** Chest Cm */
            chest_cm?: number | null;
            /** Waist Cm */
            waist_cm?: number | null;
            /** Arms Cm */
            arms_cm?: number | null;
        };
        /** ChallengeCreate */
        ChallengeCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Target Workouts
             * @default 10
             */
            target_workouts: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
        };
        /** ChallengeParticipantRead */
        ChallengeParticipantRead: {
            /** User Id */
            user_id: number;
            /** Full Name */
            full_name: string;
            /** Workouts Completed */
            workouts_completed: number;
        };
        /** ChallengeRead */
        ChallengeRead: {
            /** Id */
            id: number;
            /** Creator Id */
            creator_id: number;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Target Workouts */
            target_workouts: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Status */
            status: string;
            /**
             * Participants
             * @default []
             */
            participants: components["schemas"]["ChallengeParticipantRead"][];
            /**
             * My Workouts Completed
             * @default 0
             */
            my_workouts_completed: number;
        };
        /** DailyNutritionSummary */
        DailyNutritionSummary: {
            /**
             * Log Date
             * Format: date
             */
            log_date: string;
            /** Total Calories */
            total_calories: number;
            /** Total Protein G */
            total_protein_g: number;
            /** Total Carbs G */
            total_carbs_g: number;
            /** Total Fat G */
            total_fat_g: number;
        };
        /** DailyWorkoutPlan */
        DailyWorkoutPlan: {
            /** Day */
            day: number;
            /** Weekday */
            weekday: string;
            /** Title */
            title: string;
            /** Focus */
            focus: string;
            /** Rest */
            rest: boolean;
            /** Duration Minutes */
            duration_minutes: number;
            /** Exercises */
            exercises: components["schemas"]["PlanExercise"][];
        };
        /**
         * DifficultyLevel
         * @enum {string}
         */
        DifficultyLevel: "beginner" | "intermediate" | "advanced";
        /** EnhancedAnalytics */
        EnhancedAnalytics: {
            summary: components["schemas"]["AnalyticsSummary"];
            /** Weekly Volume */
            weekly_volume: components["schemas"]["WeeklyVolume"][];
            /** Exercise Progression */
            exercise_progression: components["schemas"]["ExerciseProgression"][];
            /** Body Trend */
            body_trend: components["schemas"]["BodyTrend"][];
            /** Streak Days */
            streak_days: number;
            /** Longest Streak */
            longest_streak: number;
        };
        /** EntitlementsResponse */
        EntitlementsResponse: {
            /** Userid */
            userId: number;
            /** Plan */
            plan: string;
            /** Status */
            status?: string | null;
            /** Storeproductid */
            storeProductId?: string | null;
            /** Currentperiodend */
            currentPeriodEnd?: string | null;
        };
        /**
         * EquipmentType
         * @enum {string}
         */
        EquipmentType: "bodyweight" | "dumbbell" | "barbell" | "machine" | "cable" | "kettlebell" | "band";
        /** ExerciseCreate */
        ExerciseCreate: {
            /** Name */
            name: string;
            muscle_group: components["schemas"]["MuscleGroup"];
            /** Secondary Muscle Groups */
            secondary_muscle_groups?: components["schemas"]["MuscleGroup"][] | null;
            /** @default bodyweight */
            equipment: components["schemas"]["EquipmentType"];
            /** @default beginner */
            difficulty: components["schemas"]["DifficultyLevel"];
            /** @default isolation */
            movement_role: components["schemas"]["MovementRole"];
            /** Video Url */
            video_url?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Instructions */
            instructions?: string | null;
            /** Alternative Exercise Id */
            alternative_exercise_id?: number | null;
        };
        /** ExerciseProgression */
        ExerciseProgression: {
            /** Exercise Id */
            exercise_id: number;
            /** Exercise Name */
            exercise_name: string;
            /** Best Weight */
            best_weight?: number | null;
            /** Best Reps */
            best_reps?: number | null;
            /**
             * Total Sets
             * @default 0
             */
            total_sets: number;
            /**
             * Sessions
             * @default 0
             */
            sessions: number;
        };
        /** ExerciseRead */
        ExerciseRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            muscle_group: components["schemas"]["MuscleGroup"];
            /** Secondary Muscle Groups */
            secondary_muscle_groups?: components["schemas"]["MuscleGroup"][] | null;
            equipment: components["schemas"]["EquipmentType"];
            difficulty: components["schemas"]["DifficultyLevel"];
            movement_role: components["schemas"]["MovementRole"];
            /** Video Url */
            video_url?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Instructions */
            instructions?: string | null;
            /** Alternative Exercise Id */
            alternative_exercise_id?: number | null;
        };
        /** FollowCreate */
        FollowCreate: {
            /** User Id */
            user_id: number;
        };
        /** GamificationSummary */
        GamificationSummary: {
            xp: components["schemas"]["UserXPRead"];
            /** Achievements */
            achievements: components["schemas"]["AchievementRead"][];
            /** Next Level Xp */
            next_level_xp: number;
        };
        /** GeneratePlanRequest */
        GeneratePlanRequest: {
            /** Days Per Week */
            days_per_week: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeaderboardEntry */
        LeaderboardEntry: {
            /** Rank */
            rank: number;
            /** User Id */
            user_id: number;
            /** Full Name */
            full_name: string;
            /** Total Xp */
            total_xp: number;
            /** Level */
            level: number;
            /** Streak Days */
            streak_days: number;
        };
        /** LogSetCreate */
        LogSetCreate: {
            /** Exercise Id */
            exercise_id: number;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Reps */
            reps: number;
            /** Set Number */
            set_number: number;
        };
        /** LogSetRead */
        LogSetRead: {
            /** Id */
            id: number;
            /** Exercise Id */
            exercise_id: number;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Reps */
            reps: number;
            /** Set Number */
            set_number: number;
            /**
             * Is Personal Record
             * @default false
             */
            is_personal_record: boolean;
        };
        /**
         * LogStatus
         * @enum {string}
         */
        LogStatus: "completed" | "partial";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MovementRole
         * @enum {string}
         */
        MovementRole: "compound" | "isolation";
        /**
         * MuscleGroup
         * @enum {string}
         */
        MuscleGroup: "chest" | "back" | "shoulders" | "biceps" | "triceps" | "forearms" | "quads" | "hamstrings" | "glutes" | "calves" | "core" | "legs" | "arms";
        /** NutritionLogCreate */
        NutritionLogCreate: {
            /**
             * Log Date
             * Format: date
             */
            log_date: string;
            /** Meal */
            meal?: string | null;
            /** Food Item */
            food_item: string;
            /**
             * Calories
             * @default 0
             */
            calories: number;
            /**
             * Protein G
             * @default 0
             */
            protein_g: number;
            /**
             * Carbs G
             * @default 0
             */
            carbs_g: number;
            /**
             * Fat G
             * @default 0
             */
            fat_g: number;
        };
        /** NutritionLogRead */
        NutritionLogRead: {
            /** Id */
            id: number;
            /**
             * Log Date
             * Format: date
             */
            log_date: string;
            /** Meal */
            meal?: string | null;
            /** Food Item */
            food_item: string;
            /** Calories */
            calories: number;
            /** Protein G */
            protein_g: number;
            /** Carbs G */
            carbs_g: number;
            /** Fat G */
            fat_g: number;
        };
        /** NutritionLogUpdate */
        NutritionLogUpdate: {
            /** Meal */
            meal?: string | null;
            /** Food Item */
            food_item?: string | null;
            /** Calories */
            calories?: number | null;
            /** Protein G */
            protein_g?: number | null;
            /** Carbs G */
            carbs_g?: number | null;
            /** Fat G */
            fat_g?: number | null;
        };
        /** PersonalRecordRead */
        PersonalRecordRead: {
            /** Id */
            id: number;
            exercise: components["schemas"]["ExerciseRead"];
            /** Weight Kg */
            weight_kg?: number | null;
            /** Reps */
            reps: number;
            /** Set Number */
            set_number: number;
            /**
             * Completed At
             * Format: date
             */
            completed_at: string;
        };
        /** PlanDayExerciseRead */
        PlanDayExerciseRead: {
            /** Id */
            id: number;
            exercise: components["schemas"]["ExerciseRead"];
            /** Sets */
            sets: number;
            /** Reps Range */
            reps_range: string;
            /** Rest Seconds */
            rest_seconds: number;
            /** Order Index */
            order_index: number;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /** Target Weight Kg */
            target_weight_kg?: number | null;
        };
        /** PlanDayExerciseUpdate */
        PlanDayExerciseUpdate: {
            /** Exercise Id */
            exercise_id?: number | null;
            /** Skipped */
            skipped?: boolean | null;
        };
        /** PlanDayRead */
        PlanDayRead: {
            /** Id */
            id: number;
            /** Day Number */
            day_number: number;
            /** Title */
            title: string;
            /** Weekday */
            weekday?: number | null;
            /** Plan Day Exercises */
            plan_day_exercises: components["schemas"]["PlanDayExerciseRead"][];
        };
        /** PlanExercise */
        PlanExercise: {
            /** Name */
            name: string;
            /** Muscle Group */
            muscle_group: string;
            /** Sets */
            sets: number;
            /** Reps */
            reps: string;
            /** Rest Seconds */
            rest_seconds: number;
        };
        /**
         * PlanStatus
         * @enum {string}
         */
        PlanStatus: "active" | "archived";
        /** PurchaseRequest */
        PurchaseRequest: {
            /** Productid */
            productId?: string | null;
        };
        /**
         * SplitType
         * @enum {string}
         */
        SplitType: "full_body" | "upper_lower" | "push_pull_legs";
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Password */
            password: string;
        };
        /** UserPublicProfile */
        UserPublicProfile: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /**
             * Total Xp
             * @default 0
             */
            total_xp: number;
            /**
             * Level
             * @default 1
             */
            level: number;
            /**
             * Streak Days
             * @default 0
             */
            streak_days: number;
            /**
             * Followers Count
             * @default 0
             */
            followers_count: number;
            /**
             * Following Count
             * @default 0
             */
            following_count: number;
            /**
             * Is Following
             * @default false
             */
            is_following: boolean;
        };
        /** UserRead */
        UserRead: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Id */
            id: number;
            /** Gender */
            gender?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Goal */
            goal?: string | null;
            /** Experience Level */
            experience_level?: string | null;
            /** Available Days Per Week */
            available_days_per_week?: number | null;
            /** Available Equipment */
            available_equipment?: string[] | null;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Gender */
            gender?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Goal */
            goal?: string | null;
            /** Experience Level */
            experience_level?: string | null;
            /** Available Days Per Week */
            available_days_per_week?: number | null;
            /** Available Equipment */
            available_equipment?: string[] | null;
        };
        /** UserXPRead */
        UserXPRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number;
            /** Total Xp */
            total_xp: number;
            /** Level */
            level: number;
            /** Streak Days */
            streak_days: number;
            /** Longest Streak */
            longest_streak: number;
            /** Last Workout Date */
            last_workout_date?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeeklyVolume */
        WeeklyVolume: {
            /** Week Start */
            week_start: string;
            /** Workouts */
            workouts: number;
            /** Total Sets */
            total_sets: number;
            /** Total Volume Kg */
            total_volume_kg: number;
        };
        /** WorkoutCreate */
        WorkoutCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Scheduled At */
            scheduled_at?: string | null;
            /**
             * Exercises
             * @default []
             */
            exercises: components["schemas"]["WorkoutExerciseCreate"][];
        };
        /** WorkoutExerciseCreate */
        WorkoutExerciseCreate: {
            /** Exercise Id */
            exercise_id: number;
            /**
             * Sets
             * @default 3
             */
            sets: number;
            /** Reps */
            reps?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
        };
        /** WorkoutExerciseRead */
        WorkoutExerciseRead: {
            /** Id */
            id: number;
            exercise: components["schemas"]["ExerciseRead"];
            /** Sets */
            sets: number;
            /** Reps */
            reps?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
        };
        /** WorkoutLogCreate */
        WorkoutLogCreate: {
            /** Plan Day Id */
            plan_day_id?: number | null;
            /** Completed At */
            completed_at?: string | null;
            /** @default completed */
            status: components["schemas"]["LogStatus"];
            /** Sets */
            sets?: components["schemas"]["LogSetCreate"][];
        };
        /** WorkoutLogRead */
        WorkoutLogRead: {
            /** Id */
            id: number;
            /** Plan Day Id */
            plan_day_id?: number | null;
            /**
             * Completed At
             * Format: date
             */
            completed_at: string;
            status: components["schemas"]["LogStatus"];
            /** Log Sets */
            log_sets: components["schemas"]["LogSetRead"][];
        };
        /** WorkoutPlanRead */
        WorkoutPlanRead: {
            /** Id */
            id: number;
            /** Days Per Week */
            days_per_week: number;
            split_type: components["schemas"]["SplitType"];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            status: components["schemas"]["PlanStatus"];
            /** Plan Days */
            plan_days: components["schemas"]["PlanDayRead"][];
        };
        /** WorkoutRead */
        WorkoutRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Scheduled At */
            scheduled_at?: string | null;
            /**
             * Exercises
             * @default []
             */
            exercises: components["schemas"]["WorkoutExerciseRead"][];
        };
        /** WorkoutSessionCreate */
        WorkoutSessionCreate: {
            /** Performed At */
            performed_at?: string | null;
            /** Notes */
            notes?: string | null;
            /** Sets */
            sets?: components["schemas"]["WorkoutSessionSetCreate"][];
        };
        /** WorkoutSessionRead */
        WorkoutSessionRead: {
            /** Id */
            id: number;
            /** Workout Id */
            workout_id: number;
            /**
             * Performed At
             * Format: date-time
             */
            performed_at: string;
            /** Notes */
            notes?: string | null;
            /** Sets */
            sets: Record<string, never>[];
        };
        /** WorkoutSessionSetCreate */
        WorkoutSessionSetCreate: {
            /** Exercise Id */
            exercise_id: number;
            /** Weight Kg */
            weight_kg?: number | null;
            /** Reps */
            reps?: number | null;
        };
        /** WorkoutUpdate */
        WorkoutUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Scheduled At */
            scheduled_at?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    update_me_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workouts_api_v1_workouts__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutRead"][];
                };
            };
        };
    };
    create_workout_api_v1_workouts__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workout_api_v1_workouts__workout_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workout_api_v1_workouts__workout_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workout_api_v1_workouts__workout_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_workouts__workout_id__sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_workouts__workout_id__sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exercises_api_v1_exercises__get: {
        parameters: {
            query?: {
                muscle_group?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_exercise_api_v1_exercises__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entry_api_v1_nutrition__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NutritionLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_for_day_api_v1_nutrition_day_get: {
        parameters: {
            query: {
                day: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyNutritionSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entries_for_day_api_v1_nutrition_day_entries_get: {
        parameters: {
            query: {
                day: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionLogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entry_api_v1_nutrition__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entry_api_v1_nutrition__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_entry_api_v1_nutrition__entry_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NutritionLogUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NutritionLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_test_api_v1_notifications_test_post: {
        parameters: {
            query: {
                workout_name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_entitlements_api_v1_entitlements_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitlementsResponse"];
                };
            };
        };
    };
    purchase_subscription_api_v1_subscriptions_purchase_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PurchaseRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitlementsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_subscription_api_v1_subscriptions_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitlementsResponse"];
                };
            };
        };
    };
    get_analytics_summary_api_v1_analytics_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummary"];
                };
            };
        };
    };
    get_enhanced_analytics_api_v1_analytics_enhanced_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnhancedAnalytics"];
                };
            };
        };
    };
    get_daily_plan_api_v1_plans_daily_get: {
        parameters: {
            query?: {
                /** @description Shift by days */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyWorkoutPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_week_api_v1_plans_week_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyWorkoutPlan"][];
                };
            };
        };
    };
    generate_api_v1_workout_plans_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneratePlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlanRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_api_v1_workout_plans_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlanRead"];
                };
            };
        };
    };
    update_plan_day_exercise_api_v1_workout_plans_plan_day_exercises__plan_day_exercise_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_day_exercise_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanDayExerciseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanDayExerciseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_logs_api_v1_workout_logs__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutLogRead"][];
                };
            };
        };
    };
    create_log_api_v1_workout_logs__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutLogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_personal_records_api_v1_workout_logs_personal_records_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalRecordRead"][];
                };
            };
        };
    };
    list_measurements_api_v1_body_measurements__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyMeasurementRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_measurement_api_v1_body_measurements__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BodyMeasurementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyMeasurementRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_api_v1_body_measurements_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyMeasurementRead"] | null;
                };
            };
        };
    };
    get_trend_api_v1_body_measurements_trend_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyMeasurementRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_measurement_api_v1_body_measurements__measurement_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                measurement_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyMeasurementRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_measurement_api_v1_body_measurements__measurement_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                measurement_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_measurement_api_v1_body_measurements__measurement_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                measurement_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BodyMeasurementUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BodyMeasurementRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gamification_api_v1_gamification_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamificationSummary"];
                };
            };
        };
    };
    follow_api_v1_social_follow_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unfollow_api_v1_social_follow__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_followers_api_v1_social_followers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublicProfile"][];
                };
            };
        };
    };
    get_following_api_v1_social_following_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublicProfile"][];
                };
            };
        };
    };
    search_users_api_v1_social_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublicProfile"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_social_profile__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublicProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_challenges_api_v1_social_challenges_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeRead"][];
                };
            };
        };
    };
    create_challenge_api_v1_social_challenges_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChallengeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_challenge_api_v1_social_challenges__challenge_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_challenge_api_v1_social_challenges__challenge_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_api_v1_social_leaderboard_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_feed_api_v1_social_feed_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
